//
//  ChildViewControllerInteractionProtocol.swift
//  ChildViewControllerInteractionProtocol
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//

import UIKit

protocol ChildViewControllerInteractionProtocol: class {
    
    func childViewControllerInteraction(controlId: String, selectedItem: Any?)
}

