//
//  Constants.swift
//  Constants
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//

class Constants {
    public static let SCENE_TYPE_SINGLE_VC = 0
    public static let SCENE_TYPE_SINGLE_VC_TAB = 1
    public static let SCENE_TYPE_MULTI_VC = 2
}

