//
//  CommonsViewController.swift
//  Commons
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//
import UIKit

class CommonsViewController: UIViewController, UITextFieldDelegate
 {

	@IBOutlet weak var calcCommButton: UIButton!
	@IBOutlet weak var firstEditText: UITextField!
	@IBOutlet weak var secondEditText: UITextField!
    @IBOutlet weak var gcfResultLabel: UILabel!
    @IBOutlet weak var lcmResultLabel: UILabel!

	
	override func viewDidLoad() {
	    super.viewDidLoad()
		calcCommButton.layer.cornerRadius = 5

        firstEditText.delegate = self
        secondEditText.delegate = self
	}
	
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}
    
    // MARK: UITextFieldDelegate
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if textField == secondEditText {
            textField.resignFirstResponder()
        } else {
            secondEditText.becomeFirstResponder()
        }
        return true
    }

	@IBAction func calcCommButtonTouchDown(_ sender: UIButton) {
        (parent as! ChildViewControllerInteractionProtocol).childViewControllerInteraction(controlId: "calcCommButton", selectedItem: nil)
    }
    
	@IBAction func calcCommButtonTouchUpInside(_ sender: UIButton) {
        //TODO Implement the action
    }  
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
}
