//
//  FractionsViewController.swift
//  Fractions
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//
import UIKit

class FractionsViewController: UIViewController, UITextFieldDelegate
 {

	@IBOutlet weak var calcFractionsButton: UIButton!
	@IBOutlet weak var decimalEditText: UITextField!
	@IBOutlet weak var numEditText: UITextField!
	@IBOutlet weak var denEditText: UITextField!
    @IBOutlet weak var dtfResultLabel: UILabel!
    @IBOutlet weak var simpleResultLabel: UILabel!
    @IBOutlet weak var ftdResultLabel: UILabel!

	
	override func viewDidLoad() {
	    super.viewDidLoad()
		calcFractionsButton.layer.cornerRadius = 5
        
        decimalEditText.delegate = self
        numEditText.delegate = self
        denEditText.delegate = self
	}
	
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}

    // MARK: UITextFieldDelegate
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if textField == decimalEditText || textField == denEditText {
            textField.resignFirstResponder()
        } else {
            denEditText.becomeFirstResponder()
        }
        return true
    }
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
        view.bounds.origin.y += decimalEditText.frame.origin.y - 10
    }
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        view.bounds.origin.y -= decimalEditText.frame.origin.y - 10
    }

	@IBAction func calcFractionsButtonTouchDown(_ sender: UIButton) {
        (parent as! ChildViewControllerInteractionProtocol).childViewControllerInteraction(controlId: "calcFractionsButton", selectedItem: nil)
    }
    
	@IBAction func calcFractionsButtonTouchUpInside(_ sender: UIButton) {
        //TODO Implement the action
    }  
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
}
