//
//  LinearViewController.swift
//  Linear
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//
import UIKit

class LinearViewController: UIViewController, UITextFieldDelegate
 {

	@IBOutlet weak var calcLEButton: UIButton!
	@IBOutlet weak var mEditText: UITextField!
	@IBOutlet weak var qEditText: UITextField!
	@IBOutlet weak var guideLEImageView: UIImageView!
    @IBOutlet weak var resultLabel: UILabel!
	
	override func viewDidLoad() {
	    super.viewDidLoad()
		calcLEButton.layer.cornerRadius = 5

        mEditText.delegate = self
        qEditText.delegate = self
	}
	
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}
    
    // MARK: UITextFieldDelegate
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if textField == qEditText {
            textField.resignFirstResponder()
        } else {
            qEditText.becomeFirstResponder()
        }
        return true
    }
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
        view.bounds.origin.y += mEditText.frame.origin.y - 10
    }
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        view.bounds.origin.y -= mEditText.frame.origin.y - 10
    }

	@IBAction func calcLEButtonTouchDown(_ sender: UIButton) {
        (parent as! ChildViewControllerInteractionProtocol).childViewControllerInteraction(controlId: "calcLEButton", selectedItem: nil)
    }
    
	@IBAction func calcLEButtonTouchUpInside(_ sender: UIButton) {
        //TODO Implement the action
    }  
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
}
