//
//  ListViewController.swift
//  List
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//
import UIKit

class ListViewController: UIViewController, UITableViewDelegate, UITableViewDataSource
 {

	@IBOutlet weak var toolsListView: UITableView!
	
	var toolsListViewContents: [String] = [
		"Fractions",
		"Probability",
		"GCF-LCM",
	]

	var toolsListViewImages: [UIImage] = [
		// Change the images for each row here
		UIImage(named: "fractions")!,
		UIImage(named: "probability")!,
		UIImage(named: "gcf")!,
	]



	
	override func viewDidLoad() {
	    super.viewDidLoad()

		self.toolsListView.delegate = self
		self.toolsListView.dataSource = self

	}
	
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}



	func numberOfSections(in tableView: UITableView) -> Int {
	    return 1
	}

	func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
	    // Return the number of rows
	    if tableView == self.toolsListView {
	        return self.toolsListViewContents.count;
	    }
	    return 0 
	}

	func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
	    // Configure the cell...
	    if tableView == self.toolsListView {
	    
	    	let toolsListViewCell = tableView.dequeueReusableCell(withIdentifier: "toolsListViewTableViewCell", for: indexPath) as! ImageTableViewCell
	        toolsListViewCell.img.image = self.toolsListViewImages[indexPath.row]
	        toolsListViewCell.label.text = self.toolsListViewContents[indexPath.row]
	        return toolsListViewCell
	        
	    }
	
	    return UITableViewCell()
	}
	
	
	func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
	    if tableView == self.toolsListView {
			(parent as! ChildViewControllerInteractionProtocol).childViewControllerInteraction(controlId: "toolsListView", selectedItem: indexPath.row)
	    }
	    tableView.deselectRow(at: indexPath, animated: true)
	}
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
}
