//
//  ProbabilityViewController.swift
//  Probability
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//
import UIKit

class ProbabilityViewController: UIViewController, UITextFieldDelegate
 {

	@IBOutlet weak var calcProbButton: UIButton!
	@IBOutlet weak var cardinalityEditText: UITextField!
	@IBOutlet weak var kEditText: UITextField!
	@IBOutlet weak var orderSwitchButton: UISwitch!
	@IBOutlet weak var repeatSwitchButton: UISwitch!
    @IBOutlet weak var resultLabel: UILabel!
	
	override func viewDidLoad() {
	    super.viewDidLoad()
		calcProbButton.layer.cornerRadius = 5

        cardinalityEditText.delegate = self
        kEditText.delegate = self
	}
	
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}

    // MARK: UITextFieldDelegate
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if textField == kEditText {
            textField.resignFirstResponder()
        } else {
            kEditText.becomeFirstResponder()
        }
        return true
    }

	@IBAction func calcProbButtonTouchDown(_ sender: UIButton) {
        (parent as! ChildViewControllerInteractionProtocol).childViewControllerInteraction(controlId: "calcProbButton", selectedItem: nil)
    }
    
	@IBAction func calcProbButtonTouchUpInside(_ sender: UIButton) {
        //TODO Implement the action
    }  
	@IBAction func orderSwitchButtonValueChangedAction(_ sender: UISwitch) {
        // You can check the value of the switch
        let isChecked: Bool = sender.isOn
    }
	@IBAction func repeatSwitchButtonValueChangedAction(_ sender: UISwitch) {
        // You can check the value of the switch
        let isChecked: Bool = sender.isOn
    }
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
}
