//
//  QuadraticViewController.swift
//  Quadratic
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//
import UIKit

class QuadraticViewController: UIViewController, UITextFieldDelegate
 {

	@IBOutlet weak var calcQEButton: UIButton!
	@IBOutlet weak var aEditText: UITextField!
	@IBOutlet weak var bEditText: UITextField!
	@IBOutlet weak var cEditText: UITextField!
	@IBOutlet weak var guideQEImageView: UIImageView!
    @IBOutlet weak var x1ResultLabel: UILabel!
    @IBOutlet weak var x2ResultLabel: UILabel!

	
	override func viewDidLoad() {
	    super.viewDidLoad()
		calcQEButton.layer.cornerRadius = 5

        aEditText.delegate = self
        bEditText.delegate = self
        cEditText.delegate = self
	}
	
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}
    
    // MARK: UITextFieldDelegate
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if textField == aEditText {
            bEditText.becomeFirstResponder()
        } else if textField == bEditText {
            cEditText.becomeFirstResponder()
        } else {
            textField.resignFirstResponder()
        }
        return true
    }
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
        view.bounds.origin.y += aEditText.frame.origin.y - 10
    }
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        view.bounds.origin.y -= aEditText.frame.origin.y - 10
    }

	@IBAction func calcQEButtonTouchDown(_ sender: UIButton) {
        (parent as! ChildViewControllerInteractionProtocol).childViewControllerInteraction(controlId: "calcQEButton", selectedItem: nil)
    }
    
	@IBAction func calcQEButtonTouchUpInside(_ sender: UIButton) {
        //TODO Implement the action
    }  
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
}
