//
//  SystemViewController.swift
//  System
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//
import UIKit

class SystemViewController: UIViewController, UITextFieldDelegate
 {

	@IBOutlet weak var calcSEButton: UIButton!
	@IBOutlet weak var a1EditText: UITextField!
	@IBOutlet weak var b1EditText: UITextField!
	@IBOutlet weak var c1EditText: UITextField!
	@IBOutlet weak var a2EditText: UITextField!
	@IBOutlet weak var b2EditText: UITextField!
	@IBOutlet weak var c2EditText: UITextField!
	@IBOutlet weak var guideSEImageView: UIImageView!
    @IBOutlet weak var xResultLabel: UILabel!
    @IBOutlet weak var yResultLabel: UILabel!

	
	override func viewDidLoad() {
	    super.viewDidLoad()
		calcSEButton.layer.cornerRadius = 5

        a1EditText.delegate = self
        b1EditText.delegate = self
        c1EditText.delegate = self
        a2EditText.delegate = self
        b2EditText.delegate = self
        c2EditText.delegate = self
	}
	
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}
    
    // MARK: UITextFieldDelegate
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if textField == a1EditText {
            b1EditText.becomeFirstResponder()
        } else if textField == b1EditText {
            c1EditText.becomeFirstResponder()
        } else if textField == c1EditText {
            a2EditText.becomeFirstResponder()
        } else if textField == a2EditText {
            b2EditText.becomeFirstResponder()
        } else if textField == b2EditText {
            c2EditText.becomeFirstResponder()
        } else {
            textField.resignFirstResponder()
        }
        return true
    }
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
        view.bounds.origin.y += a1EditText.frame.origin.y - 10
    }
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        view.bounds.origin.y -= a1EditText.frame.origin.y - 10
    }

	@IBAction func calcSEButtonTouchDown(_ sender: UIButton) {
        (parent as! ChildViewControllerInteractionProtocol).childViewControllerInteraction(controlId: "calcSEButton", selectedItem: nil)
    }
    
	@IBAction func calcSEButtonTouchUpInside(_ sender: UIButton) {
        //TODO Implement the action
    }  
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
}
