//
//  WebsitesViewController.swift
//  Websites
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//
import UIKit

class WebsitesViewController: UIViewController
 {

	@IBOutlet weak var webView: UIWebView!

	
	override func viewDidLoad() {
	    super.viewDidLoad()


		changePageURL(url: "http://www.youmath.it/lezioni/algebra-elementare")
	}
	
	override func viewDidAppear(_ animated: Bool) {
	    super.viewDidAppear(animated)
	}
	
	override func viewDidDisappear(_ animated: Bool) {
		super.viewDidDisappear(animated)
	}

	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
	}
	
	override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
	}
	
	override func didReceiveMemoryWarning() {
	    super.didReceiveMemoryWarning()
	    // Dispose of any resources that can be recreated.
	}
    
    func changePageURL(url: String) {
        let url = URL(string: url)
        if let unwrappedURL = url {
            let request = URLRequest(url: unwrappedURL)
            let session = URLSession.shared
            let task = session.dataTask(with: request) { (data, response, error) in
                if error == nil {
                    self.webView.loadRequest(request)
                } else {
                    print("ERROR \(error)")
                }
            }
            task.resume()
        }
    }
}
