//
//  MenuInteractionProtocol.swift
//  MenuInteractionProtocol
//
//  Automatically generated by MobileCodeGenerator 4.
//  Copyright 2018 . All rights reserved.
//

import UIKit

protocol MenuInteractionProtocol: class {
    
    func menuInteraction(_ item: String)
}

